### model
model_name_or_path: /home/qwe/test/pretrained_model/Llama-3-8B-Instruct
adapter_name_or_path: /home/qwe/test/zpwang/LLaMA/exp_space/baseline.old

### method
stage: sft
do_train: false
predict_with_generate: true
finetuning_type: lora
lora_target: all

### dataset
dataset: pdtb3.top.2024_06_11_21_41_36.base.clip2048
template: llama3
cutoff_len: 2048
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/qwe/test/zpwang/LLaMA/exp_space/baseline
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
